version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - default

  api-service:
    container_name: api-service
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql
    env_file:
      - .env
    ports:
      - '8080:8080'
    networks:
      - default

#  prometheus:
#    image: "prom/prometheus"
#    container_name: prometheus
#    restart: unless-stopped
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    ports:
#      - '9090:9090'
#    networks:
#      - default
#
#  grafana:
#    image: "grafana/grafana"
#    container_name: grafana
#    restart: unless-stopped
#    environment:
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_SECURITY_ADMIN_PASSWORD=password
#    ports:
#      - '3000:3000'
#    links:
#      - prometheus:prometheus
#    volumes:
#      - grafana:/var/lib/grafana
#    networks:
#      - default

networks:
  default:
    name: api-network

volumes:
  mysql_data:
#  grafana:
